dependencies:
  - name: rabbitmq-ha
    version: 1.36.4
    repository: https://kubernetes-charts.storage.googleapis.com/
    condition: rabbitmq-ha.enabled
  - name: external-dns
    version: 1.6.1
    repository: https://kubernetes-charts.storage.googleapis.com/
    condition: external-dns.enabled
  - name: etcd-operator
    version: 0.10.0
    repository: https://kubernetes-charts.storage.googleapis.com/
